### ISSUE TITLE
Assign "SCM" field to functions via github-push

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#210]
## Expected Behaviour

We should assign an "SCM" field to functions via `github-push` so that we can use this information for re-constituting links later on.

For example:

```go
prefix + "scm" = "github"
```

## Current Behaviour

We assume only GitHub, but have support for GitLab via #101 - this means dashboard links etc are wrong when using GitLab - they are instead directed to GitHub.

For GitLab we may need to have a further field such as "SCM address" since I expect the integrated GitLab instance to be something running at an address like: https://gitlab.team-serverless.xyz. GitHub will always be https://github.com/

## Possible Solution

Please provide some ideas / suggestions on above.

**Comment by alexellis** [comment]
cc @bartsmykla @martindekov

**Comment by alexellis** [comment]
@martindekov please can you take this?

**Comment by martindekov** [comment]
Yeah

**Comment by martindekov** [comment]
Derek assign: me

**Comment by alexellis** [comment]
Source Control Management i.e. GitHub / GitLab / BitBucket

**Comment by martindekov** [comment]
I was wondering if it is better approach to just handle whole URL to the repository path instead of constructing the URL? GitLab provides the repo URL in its payload:
```
...
      "web_url":"https://gitlab.team-serverless.xyz/martindekov/gitlab-tag-event",
...
```
and github provides the URL in its payload:
```
...
    "html_url": "https://github.com/martindekov/gocloudfunc",
...
```
Of course this will require change in the dashboards but they would be minor and @bartsmykla agreed on helping me integrating this into the dashboard.
