### ISSUE TITLE
Feature: GitLab CI/CD support

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#225]
Part 1 - After a planning meeting with the FaaS team, we want to restrict gitlab-push to only work for repos that are tagged as "openfaas-cloud". Builds upon #109 which is working 👍 

Part 2 - We need to garbage collect repos / functions when the tag is removed.
Tag events are sent via System Hooks.

Part 3 - we will need to document how to deploy OpenFaaS Cloud for GitLab as an alternative to GitHub - this needs to be structured appropriately in the docs/README.md file.

**Comment by alexellis** [comment]
Diagram outlining the differences in approach and events for integrating with GitHub vs GitLab.

Note that GitLab will have a custom URL.

![github _ gitlab](https://user-images.githubusercontent.com/6358735/46202592-29528600-c30f-11e8-90e4-0141b876e511.png)

**Comment by martindekov** [comment]
Ran some tests and concluded the following things:

• Tagging wont send any form of tag with Push hook so every time push appears we will build no matter if the tag is present or not

Two approaches that come to mind:

1. Adding in repository description : `Install` or `OF-Cloud` or something like that 
• Pros: Simple 
• Cons: Need to push on install/uninstall and loss of description if needed

2. Storing on tag event the repository that was tagged in database or file or something and do the following:
• Add tag -> `push_tag_event` -> `(value == Cloud) ?  (y -> modify file tag = sha1=asdzxc and build function) , (n -> not the tag we need) `
• Push some change to the code, check file first `(value == 00000) ?  (y -> do nothing) , (n -> build change) `
• Remove tag ->  `push_tag_event` -> `(value == Cloud) ?  (y -> modify file = 000 and remove function) , (n -> not the tag we need) `
• Push some change to the code, check file first `(value == 00000) ?  (y -> do nothing) , (n -> build change) `

I think file for every user over database since we don't have so much information to store. This is in case we want to "install" the app for the whole gitlab instance like for example `https://gitlab.team-serverless.xyz/` one.

Those are the things that I can think of for now, but will investigate more tomorrow.

**Comment by alexellis** [comment]
Have you thought of querying tags on the GitLab repo URL when you get a push event?

Are you saying that push events never contain the tags for the repo? (I thought we may have seen that when debugging)

**Comment by alexellis** [comment]
Have a look at this endpoint in the API, you can use it to look at tags every system push event - https://docs.gitlab.com/ee/api/projects.html#get-single-project

**Comment by martindekov** [comment]
In this situation in every event we should call the API of gitlab, and sometimes for some reason gitlab is sending couple of the same events. Also need to fix the optimisation that is checking the `stack.yml` and will probably open issue for that. Maybe send raw `stack.yml` in github-push rather than testing it directly in git-tar. Also will update the PR with how the current function works through diagram
