### ISSUE TITLE
GitHub Checks: dashboard link is incorrect

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#322]
## Expected Behaviour

I expected the dashboard link to go to https://system.o6s.io/dashboard/user-name

## Current Behaviour

It was going to the root domain of my name i.e. https://user-name.o6s.io/

<img width="806" alt="screen shot 2018-10-31 at 10 18 25 am" src="https://user-images.githubusercontent.com/6358735/47781772-7783ec00-dcf6-11e8-9728-17fd57d65d5f.png">

**Comment by alexellis** [comment]
@ivanayov can you look into git blame and find out what happened? Is this a code or config issue?

**Comment by ivanayov** [comment]
It's both. Needs fixing [buildPublicStatusURL](https://github.com/openfaas/openfaas-cloud/blob/master/github-status/handler.go#L121) and change of `gateway_public_url` to `https://system.o6s.io/`

The latest change is [here](https://github.com/openfaas/openfaas-cloud/commit/f48820aabe6cd105ecfa46d5b40263ea22f62615) (search for `buildPublicStatusURL`), but the problem comes from the routing changes I think.

I've changed `buildPublicStatusURL`, but still have to add some more test coverage. 
If I have a chance tomorrow, will have a look at it after the Workshop.
