### ISSUE TITLE
Spike/research: how would a polling model work for CI/CD?

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#471]
## Potential opportunity 

We could integrate with any accessible git repository / hosting system, if we implemented a pulling / polling method as an alternative to push-based access.

## Current Behaviour

Push based only, supporting GitHub.com and GitLab self-hosted.

This model only needs one hook per system, however a pull-based model needs a trigger for every git repository and this could become hard to manage. 

## Possible Solution

Experiment with a git repository on Azure DevOps or Bitbucket, or gitlab.com for instance.

We need to find a way to bind a secret and a set of git repository URLs.

**Comment by matipan** [comment]
We would also need to have some kind of persistence for recording which was the last commit that was successfully built. Also, if the build takes longer than the polling interval we are going to creating builds that point to the same commit so we might want to create some form of lock so that new builds don't start if there is one already running.
