### ISSUE TITLE
Proposal:  Case insensitive username handling

### ISSUE THREAD

**Issue by affix** [openfaas/openfaas-cloud#54]
We should handle usernames as case insensitive from the CUSTOMERS File

```
Affix
affix
aFfIx
```

should all match to affix

gh-push handler.go line 62

```go
for _, customer := range customers {
	if customer == pushEvent.Repository.Owner.Login {
		found = true
	}
}
```

should be

```go
for _, customer := range customers {
	if strings.EqualFold(customer, pushEvent.Repository.Owner.Login) {
		found = true
	}
}
```

**Comment by viveksyngh** [comment]
Derek add label: proposal

**Comment by alexellis** [comment]
Please can you research this item @burtonr? 

I think that some kind of mapping would probably be necessary, but I'm not sure.

Also we access a user's functions via a URL like: username.domain/function - we can't have a mixed-case sub-domain host in a URL, so it would have to always be lower here too. Mixed-case is fine in the function name.

**Comment by burtonr** [comment]
I'm on it :smile: 

I believe, that since Github's usernames are case-insensitive, we should be able to just make the usernames lowercase and it _should_ "just work". I'm setting up an instance of-cloud to test that theory with and will submit the PR once I've been able to verify

**Comment by alexellis** [comment]
I just tried setting image name to lowercase in of-builder, it gets us most of the way, then there's of-router which only works with lowercase since we use a subdomain per user.

**Comment by alexellis** [comment]
@burtonr It's been just over a week so I thought I'd see how things are going? Can you give an update?

**Comment by alexellis** [comment]
We have other people that need this too like @OmgImAlexis

**Comment by alexellis** [comment]
Thanks. We may have made that harder by moving the post a bit - just merged a new set of features via @s8sg to implement multiple statuses.

**Comment by burtonr** [comment]
@alexellis I'm going to need to step down from this issue. I cannot reliably deploy OpenFaaS-Cloud right now, and therefor cannot test any changes I make.

I'm using Azure's AKS, but it is proven over and over again to be unreliable. I've been fighting issues with that platform for several days. I've also spent the entirety of my credit setting up and tearing down clusters trying to get it to work. 

I will continue to find a better solution so that I may contribute to this project in the future, but I don't want anyone waiting for me any longer for this.

**Comment by burtonr** [comment]
Derek unassign: me
