### ISSUE TITLE
[Community Suggestion] Gitea support

### ISSUE THREAD

**Issue by v7lin** [openfaas/openfaas-cloud#642]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
@v7lin thank you for your interest, could you provide a link to the project, and a little more context?

Why do you feel this should be added? Are you going to sponsor or contribute the feature?

What are the interfaces for Gitea compared to GitHub/GitLab? Is it even possible to add system-level integrations?

See also: [how to write a proposal](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md#i-have-a-great-idea)

**Comment by brandonkal** [comment]
[Gitea](https://github.com/go-gitea/gitea) is an interesting project. It is essentially another git-in-the-browser host with a UI that mimics GitHub. It started as a fork of the Gogs project and is very lightweight compared to say self-hosting a GitLab instance on Kubernetes. It doesn't offer anywhere near as much as GitLab, but it also doesn't need a pile of RAM like the big two.

I have considered contributing this feature in the past and have experimented with an OFC + Gitea deployment.
OFC just doesn't fit well with Gitea. In many ways OFC is redundant to simpler solutions. Strip out the routing portion of this into a distinct thing and let Gitea handle the auth (or defer to GitHub).

Ultimately, I have decided against suggesting adding Gitea to OFC.
- Gitea is lightweight and already has an excellent Drone CI integration.
- OFC is already quite complex with GitHub and GitLab, which covers the mainstream.
- I'm much more interested in seeing OFC broken down into its useful components. In this case you would just need routing + a metrics dashboard.

**Comment by alexellis** [comment]
I am not sure that I agree with the statement: "OFC just doesn't fit well with Gitea", I think it's the opposite:

* Gitea has no API integration at the system level
* Gitea has no OAuth API
* Gitea looks like a toy in comparison to GitLab (what organisation would use it instead of GitLab or BitBucket?)

If you want to see use individual components of OFC in your pipelines @brandonkal then go ahead, nobody is stopping you. There are even issues in the roadmap for this and on the repo, if you search.

> you would just need routing + a metrics dashboard

I love that word "just" - so once you just add CI, CD, "routing", metrics, auth and a dashboard, you have now rebuilt OpenFaaS Cloud. 

Happy for you to take the discussion to Slack in #contributors or #openfaas-cloud, or comment on the issues in this repo or on the Trello roadmap. Contributions are welcome.

**Comment by alexellis** [comment]
See also: https://github.com/openfaas/openfaas-cloud/issues/440

**Comment by alexellis** [comment]
I'm locking this issue as Gitea doesn't appear to have the requisite APIs to integrate with OFC and the rest of the discussion "run parts of OFC on their own" is off-topic".

As mentioned to @brandonkal that doesn't mean that people can't try to run parts of the OFC project on their own terms, it's open source and folks are welcome to do what they like with the code.

For hacking off individual components on OFC and running them separately, there are already issues open for this, folks feel free to contribute. 

As for roadmap, I can't see Gitea as a good fit for the time being.
